name: ne_spectrum_scRNAseq
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - matplotlib-base
  - numba
  - numpy
  - numpy-base
  - opentsne
  - pandas
  - pip
  - python>=3.12
  - python
  - pytorch
  #- pytorch-cuda
  - cudatoolkit
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - torchvision
  - yaml
  - anndata
  - scanpy=1.9.3
  - ffmpeg
  - pip:
      - ne-spectrum
